// Complete exhaustive dictionary for air compressor parts translation
export const fullIndustrialDict = [
  // 1. Bình & Bể chứa
  { vi: 'bình khí nén không gỉ', en: 'Stainless Steel Air Receiver Tank', zh: '304不锈钢高压储气罐' },
  { vi: 'bình khí nén inox', en: 'Stainless Steel Air Receiver Tank', zh: '304不锈钢高压储气罐' },
  { vi: 'bình khí nén không rỉ', en: 'Stainless Steel Air Receiver Tank', zh: '304不锈钢高压储气罐' },
  { vi: 'bình khí nén', en: 'Compressed Air Receiver Tank', zh: '工业高压压缩空气储气罐' },
  { vi: 'bình chứa khí nén', en: 'Compressed Air Receiver Tank', zh: '工业压缩空气储气罐' },
  { vi: 'bình tích khí', en: 'Air Receiver Tank', zh: '储气罐' },
  { vi: 'bình tách dầu', en: 'Air-Oil Separator Vessel', zh: '油气分离桶' },
  { vi: 'bình chứa khí', en: 'Air Receiver Tank', zh: '储气罐' },
  { vi: 'bình chứa', en: 'Air Vessel Tank', zh: '储气罐' },

  // 2. Bộ lọc, Tách nước, Cốc lọc
  { vi: 'bộ tách nước khí nén', en: 'Compressed Air Moisture Separator', zh: '压缩空气气水分离器' },
  { vi: 'bộ tách nước', en: 'Moisture Separator', zh: '气水分离器' },
  { vi: 'bộ lọc đường ống khí nén', en: 'Inline Compressed Air Filter System', zh: '压缩空气精密管道过滤器组' },
  { vi: 'bộ lọc đường ống', en: 'Inline Air Filter System', zh: '精密管道过滤器组' },
  { vi: 'bộ lọc tách dầu', en: 'Air-Oil Separator Kit', zh: '油气分离器总成' },
  { vi: 'bộ lọc tách', en: 'Air-Oil Separator Kit', zh: '油气分离器总成' },
  { vi: 'bộ xả nước tự động', en: 'Automatic Drain Valve Assembly', zh: '自动排水器总成' },
  { vi: 'bộ xả nước', en: 'Drain Valve Kit', zh: '排水器总成' },
  { vi: 'bộ lọc khí', en: 'Air Filter Set', zh: '空气过滤器组' },
  { vi: 'bộ lọc', en: 'Filter Set', zh: '过滤器总成' },
  { vi: 'cốc xả nước tự động', en: 'Auto Drain Filter Bowl', zh: '自动排水器水杯' },
  { vi: 'cốc xả nước', en: 'Drain Filter Bowl', zh: '排水器滤杯' },
  { vi: 'cốc lọc đường ống', en: 'Inline Filter Housing Bowl', zh: '管道过滤器滤杯外壳' },
  { vi: 'cốc lọc', en: 'Filter Housing Bowl', zh: '过滤器滤杯' },
  { vi: 'lõi lọc đường ống', en: 'Inline Filter Element', zh: '管道精密滤芯' },
  { vi: 'lõi lọc', en: 'Filter Element', zh: '滤芯' },
  { vi: 'lọc tách dầu', en: 'Air-Oil Separator', zh: '油气分离芯 (油分芯)' },
  { vi: 'lọc tách nhớt', en: 'Air-Oil Separator', zh: '油气分离芯 (油分芯)' },
  { vi: 'lọc tách', en: 'Air-Oil Separator', zh: '油气分离芯' },
  { vi: 'tách dầu', en: 'Air-Oil Separator', zh: '油气分离芯' },
  { vi: 'tách nhớt', en: 'Air-Oil Separator', zh: '油气分离芯' },
  { vi: 'lọc dầu', en: 'Oil Filter', zh: '机油滤清器 (油滤)' },
  { vi: 'lọc nhớt', en: 'Oil Filter', zh: '机油滤清器 (油滤)' },
  { vi: 'lọc gió', en: 'Air Intake Filter', zh: '空气滤清器 (空滤)' },
  { vi: 'lọc khí', en: 'Air Filter', zh: '空气过滤器' },

  // 3. Phao, Van, Khớp, Đấu nối
  { vi: 'phao xả nước tự động', en: 'Float Auto Drain Valve', zh: '浮球式自动排水阀' },
  { vi: 'phao xả nước', en: 'Float Drain Valve', zh: '浮球排水阀' },
  { vi: 'phao xả', en: 'Float Drainer', zh: '浮球排水器' },
  { vi: 'công tắc áp suất', en: 'Pressure Switch Controller', zh: '压力开关控制器' },
  { vi: 'công tắc áp', en: 'Pressure Switch', zh: '压力开关' },
  { vi: 'rơ le máy nén khí', en: 'Air Compressor Pressure Switch', zh: '空压机压力开关继电器' },
  { vi: 'rơle máy nén khí', en: 'Air Compressor Pressure Switch', zh: '空压机压力开关继电器' },
  { vi: 'rơ le áp suất', en: 'Pressure Switch', zh: '压力开关继电器' },
  { vi: 'rơle áp suất', en: 'Pressure Switch', zh: '压力开关继电器' },
  { vi: 'rơ le nhiệt', en: 'Thermal Overload Relay', zh: '热过载继电器' },
  { vi: 'rơle nhiệt', en: 'Thermal Overload Relay', zh: '热过载继电器' },
  { vi: 'rơ le', en: 'Pressure Switch / Relay', zh: '压力继电器' },
  { vi: 'rơle', en: 'Pressure Switch / Relay', zh: '压力继电器' },
  { vi: 'van an toàn xả áp', en: 'Safety Relief Valve', zh: '安全泄放阀' },
  { vi: 'van an toàn', en: 'Safety Valve', zh: '安全阀' },
  { vi: 'van xả nước tự động', en: 'Auto Drain Valve', zh: '自动排水阀' },
  { vi: 'van xả tự động', en: 'Auto Drain Valve', zh: '自动排水阀' },
  { vi: 'van xả nước', en: 'Drain Valve', zh: '排水阀' },
  { vi: 'van điện từ', en: 'Solenoid Valve', zh: '电磁控制阀' },
  { vi: 'van hằng nhiệt', en: 'Thermostatic Valve', zh: '自动温控阀' },
  { vi: 'van nhiệt', en: 'Thermostatic Valve', zh: '温控阀' },
  { vi: 'van một chiều', en: 'Check Valve', zh: '单向止回阀' },
  { vi: 'van hút', en: 'Air Intake Valve', zh: '进气控制阀' },
  { vi: 'van cổ hút', en: 'Air Intake Valve', zh: '进气控制阀' },
  { vi: 'cổ hút máy nén khí', en: 'Air Compressor Intake Valve Assembly', zh: '螺杆空压机进气阀总成' },
  { vi: 'cổ hút', en: 'Air Intake Valve', zh: '进气阀总成' },
  { vi: 'van áp suất tối thiểu', en: 'Minimum Pressure Valve', zh: '最小压力维持阀 (MPV)' },
  { vi: 'van điều áp', en: 'Pressure Regulating Valve', zh: '精密气动调压阀' },
  { vi: 'van tiết lưu', en: 'Throttle Valve', zh: '节流阀' },
  { vi: 'van xả tải', en: 'Blowdown Valve', zh: '放空阀' },
  { vi: 'van', en: 'Valve', zh: '阀门' },

  // 4. Cơ khí, Động cơ, Mô tơ, Đầu nén, Bơm mỡ
  { vi: 'mô tơ máy nén khí', en: 'Air Compressor Drive Motor', zh: '空压机三相异步驱动电机' },
  { vi: 'mô tơ', en: 'Electric Motor', zh: '驱动电机' },
  { vi: 'motor', en: 'Electric Motor', zh: '驱动电机' },
  { vi: 'động cơ điện', en: 'Electric Motor', zh: '高效驱动电机' },
  { vi: 'đầu máy nén khí', en: 'Air Compressor Pump Block Head', zh: '空压机机头主机总成' },
  { vi: 'đầu nén trục vít', en: 'Screw Air-End Block', zh: '螺杆机头主机' },
  { vi: 'đầu nén', en: 'Air-End Block', zh: '压缩机头' },
  { vi: 'đầu bơm mỡ', en: 'Grease Gun Coupler Nozzle', zh: '高压黄油枪注油嘴' },
  { vi: 'đầu nối nhanh', en: 'Quick Coupler Fitting', zh: '气动快速接头' },
  { vi: 'đầu nối', en: 'Pneumatic Fittings / Connector', zh: '气动接头' },
  { vi: 'đầu bơm', en: 'Pump Head', zh: '泵头' },
  { vi: 'đầu', en: 'Head / Block', zh: '机头/接头' },

  // 5. Ống, Dây, Cuộn dây
  { vi: 'ống pu cuộn', en: 'PU Pneumatic Hose Coil', zh: 'PU气动软管卷 (聚氨酯管)' },
  { vi: 'ống pu', en: 'PU Pneumatic Hose', zh: 'PU气动软管' },
  { vi: 'ống hút gió máy nén khí', en: 'Air Compressor Intake Hose', zh: '空压机进气软管' },
  { vi: 'ống hút gió', en: 'Air Intake Hose', zh: '进气软管' },
  { vi: 'ống dẫn dầu', en: 'High Pressure Oil Hose', zh: '高压耐油软管' },
  { vi: 'ống dẫn khí', en: 'Pneumatic Air Hose', zh: '气动耐压软管' },
  { vi: 'ống mềm', en: 'Flexible Hose', zh: '柔性软管' },
  { vi: 'ống', en: 'Hose / Pipe', zh: '软管/管路' },
  { vi: 'dây phun khí', en: 'High-Pressure Air Spray Hose', zh: '高压气动喷气软管 (风带)' },
  { vi: 'dây dẫn mỡ', en: 'High-Pressure Grease Hose', zh: '高压注脂软管 (黄油管)' },
  { vi: 'dây curoa', en: 'Industrial Drive V-Belt', zh: '工业三角传动皮带' },
  { vi: 'dây đai răng cưa', en: 'Cogged Drive Belt', zh: '齿形切边传动皮带' },
  { vi: 'dây đai truyền động', en: 'Drive Belt', zh: '传动皮带' },
  { vi: 'dây đai', en: 'Drive Belt', zh: '传动皮带' },
  { vi: 'ròng rọc hơi', en: 'Automatic Air Hose Reel', zh: '自动回卷气管卷轴 (气鼓)' },
  { vi: 'ròng rọc', en: 'Hose Reel', zh: '气管卷轴' },
  { vi: 'cuộn dây hơi', en: 'Air Hose Reel', zh: '自动卷气管器' },
  { vi: 'dây hơi', en: 'Air Hose', zh: '气动软管' },

  // 6. Phớt, Gioăng, Ron, Bạc đạn, Xi lanh
  { vi: 'phớt chặn dầu', en: 'Air-End Shaft Oil Seal', zh: '轴端骨架油封' },
  { vi: 'phớt chắn dầu', en: 'Air-End Shaft Oil Seal', zh: '轴端骨架油封' },
  { vi: 'phớt chặn', en: 'Oil Seal', zh: '骨架油封' },
  { vi: 'phớt chắn', en: 'Oil Seal', zh: '骨架油封' },
  { vi: 'phớt', en: 'Seal', zh: '油封/密封件' },
  { vi: 'ron đầu nén', en: 'Air-End Gasket Set', zh: '压缩机头密封垫片包' },
  { vi: 'bộ ron', en: 'Full Gasket Kit', zh: '全套密封垫片包' },
  { vi: 'ron phớt', en: 'Gaskets & Seals', zh: '密封圈与垫片' },
  { vi: 'ron', en: 'Gasket / O-Ring', zh: '密封垫片' },
  { vi: 'gioăng phớt', en: 'Gaskets & Seals', zh: '密封圈与垫片' },
  { vi: 'gioăng', en: 'Gasket / O-Ring', zh: '密封垫片' },
  { vi: 'bạc đạn đầu nén', en: 'Air-End Heavy Duty Bearings', zh: '主机转子重载轴承' },
  { vi: 'bạc đạn', en: 'Bearings', zh: '重载轴承' },
  { vi: 'vòng bi', en: 'Bearings', zh: '重载轴承' },
  { vi: 'xi lanh máy nén khí piston', en: 'Piston Compressor Cylinder', zh: '活塞式空压机气缸' },
  { vi: 'xi lanh máy nén khí', en: 'Air Compressor Cylinder', zh: '空压机气缸' },
  { vi: 'xi lanh', en: 'Cylinder', zh: '气缸' },
  { vi: 'xylanh', en: 'Cylinder', zh: '气缸' },
  { vi: 'piston', en: 'Piston Assembly', zh: '活塞组件' },
  { vi: 'xéc măng', en: 'Piston Rings', zh: '活塞环' },
  { vi: 'bánh răng chủ động', en: 'Driving Gear', zh: '主动传动齿轮' },
  { vi: 'bánh răng', en: 'Transmission Gear', zh: '传动齿轮' },
  { vi: 'khớp nối mềm', en: 'Flexible Coupling', zh: '弹性联轴器' },
  { vi: 'khớp nối', en: 'Coupling', zh: '联轴器' },

  // 7. Giải nhiệt, Quạt, Dầu & Hạt hút ẩm
  { vi: 'dàn trao đổi nhiệt', en: 'Heat Exchanger Cooler Matrix', zh: '铝制换热器 (油气冷却器)' },
  { vi: 'dàn giải nhiệt', en: 'Cooler Matrix', zh: '散热排/冷却器' },
  { vi: 'két giải nhiệt dầu', en: 'Oil Cooler Heat Exchanger', zh: '机油散热冷却器' },
  { vi: 'két giải nhiệt', en: 'Heat Exchanger Cooler', zh: '散热冷却器' },
  { vi: 'két làm mát', en: 'Air/Oil Cooler', zh: '风冷散热器' },
  { vi: 'quạt giải nhiệt', en: 'Cooling Fan Assembly', zh: '散热冷却风扇' },
  { vi: 'quạt làm mát', en: 'Cooling Fan Assembly', zh: '冷却风机' },
  { vi: 'quạt', en: 'Cooling Fan', zh: '冷却风扇' },
  { vi: 'hạt hút ẩm', en: 'Desiccant Alumina Beads', zh: '高效活性氧化铝吸附干燥颗粒 (吸附剂)' },
  { vi: 'chất hút ẩm', en: 'Desiccant Beads', zh: '吸附干燥剂' },
  { vi: 'dầu máy nén khí fusheng', en: 'Genuine Fusheng Air Compressor Oil', zh: '正品复盛 (Fusheng) 螺杆空压机专用油' },
  { vi: 'dầu fusheng', en: 'Genuine Fusheng Lubricant Oil', zh: '正品复盛 (Fusheng) 专用机油' },
  { vi: 'dầu máy nén khí trục vít', en: 'Screw Compressor Synthetic Oil', zh: '螺杆空压机专用合成润滑油' },
  { vi: 'dầu máy nén khí', en: 'Air Compressor Lubricant Oil', zh: '空压机专用润滑油' },
  { vi: 'dầu bôi trơn', en: 'Lubricant Oil', zh: '专用润滑油' },
  { vi: 'dầu làm mát', en: 'Cooling Lubricant', zh: '冷却润滑油' },
  { vi: 'dầu', en: 'Lubricant Oil', zh: '专用润滑油' },
  { vi: 'nhớt', en: 'Lubricant Oil', zh: '专用润滑油' },

  // 8. Màn hình, Cảm biến, Đồng hồ
  { vi: 'màn hình điều khiển', en: 'PLC Controller Display Panel', zh: 'PLC微电脑控制器显示屏 (控制面板)' },
  { vi: 'màn hình plc', en: 'PLC Controller Display', zh: 'PLC控制器显示屏' },
  { vi: 'màn hình', en: 'Display Screen', zh: '显示屏' },
  { vi: 'bảng điều khiển', en: 'Control Panel', zh: '控制面板' },
  { vi: 'cảm biến áp suất khí nén', en: 'Pressure Transmitter', zh: '空压机压力变送器' },
  { vi: 'cảm biến áp suất', en: 'Pressure Sensor', zh: '压力传感器' },
  { vi: 'cảm biến nhiệt độ', en: 'Temperature Sensor', zh: '温度传感器' },
  { vi: 'cảm biến', en: 'Sensor', zh: '传感器' },
  { vi: 'đồng hồ đo áp suất máy nén khí', en: 'Air Compressor Pressure Gauge', zh: '空压机高精度防震压力表' },
  { vi: 'đồng hồ đo áp suất', en: 'Pressure Gauge', zh: '高精度防震压力表' },
  { vi: 'đồng hồ áp suất', en: 'Pressure Gauge', zh: '防震压力表' },
  { vi: 'đồng hồ áp', en: 'Pressure Gauge', zh: '压力表' },
  { vi: 'thước đo mức dầu', en: 'Oil Level Sight Glass Gauge', zh: '玻璃管油位计/观油镜' },
  { vi: 'thước thăm dầu', en: 'Oil Level Gauge', zh: '油位计/观油镜' },
  { vi: 'mắt thăm dầu', en: 'Oil Sight Glass', zh: '观油镜' },

  // 9. Máy móc
  { vi: 'máy nén khí piston', en: 'Piston Air Compressor', zh: '活塞式空压机' },
  { vi: 'máy nén khí trục vít', en: 'Screw Air Compressor', zh: '螺杆式空压机' },
  { vi: 'máy nén khí không dầu', en: 'Oil-Free Air Compressor', zh: '无油空压机' },
  { vi: 'máy nén khí cao áp', en: 'High-Pressure Air Compressor', zh: '高压空压机' },
  { vi: 'máy sấy khí nén tác nhân lạnh', en: 'Refrigerated Air Dryer', zh: '冷冻式干燥机' },
  { vi: 'máy sấy khí hấp thụ', en: 'Desiccant Air Dryer', zh: '吸附式干燥机' },
  { vi: 'máy sấy khí', en: 'Compressed Air Dryer', zh: '冷干机' },
  { vi: 'máy nén khí', en: 'Air Compressor', zh: '空压机' },
  { vi: 'máy nén', en: 'Compressor', zh: '空压机' },
  { vi: 'biến tần', en: 'VFD Inverter', zh: '变频器' },

  // 10. Chất liệu, Thuộc tính, Xuất xứ
  { vi: 'không gỉ', en: 'Stainless Steel', zh: '不锈钢' },
  { vi: 'inox', en: 'Stainless Steel (304)', zh: '304不锈钢' },
  { vi: 'đồng thau', en: 'Brass', zh: '黄铜' },
  { vi: 'đồng', en: 'Copper / Brass', zh: '铜制' },
  { vi: 'nhôm', en: 'Aluminum', zh: '铝制' },
  { vi: 'thép', en: 'Steel', zh: '钢制' },
  { vi: 'thủy tinh', en: 'Glass', zh: '防爆玻璃' },
  { vi: 'cao su', en: 'Rubber', zh: '橡胶' },
  { vi: 'chính hãng', en: 'Genuine', zh: '正品原装' },
  { vi: 'cao cấp', en: 'Premium', zh: '高品质' },
  { vi: 'tự động', en: 'Automatic', zh: '自动' },
  { vi: 'công nghiệp', en: 'Industrial', zh: '工业级' },
  { vi: 'chịu nhiệt', en: 'Heat-Resistant', zh: '耐高温' }
];

console.log('Dict loaded successfully');
